#!/usr/bin/env bash
# Generate overlay_files.c from every .ko under <srcdir>/modules/.
# Each module is embedded raw as a const byte array plus an entry in
# overlay_file_list[]. Invoked by the Makefile:
#   convert_overlay.sh <output.c> <srcdir>
# Uses only python3 (no zstd/xxd dependency).
set -e

OUT="$1"
SRC="$2"
SRC="${SRC%\"}"; SRC="${SRC#\"}"
MODDIR="$SRC/modules"

python3 - "$OUT" "$MODDIR" <<'PYEOF'
import os, sys, glob

out_path, moddir = sys.argv[1], sys.argv[2]
kos = sorted(glob.glob(os.path.join(moddir, "*.ko")))

lines = []
lines.append("// SPDX-License-Identifier: GPL-2.0")
lines.append("// AUTO-GENERATED by convert_overlay.sh - do not edit.")
lines.append('#include "overlay_files.h"')
lines.append("")

entries = []
for ko in kos:
    base = os.path.basename(ko)[:-3]          # strip .ko
    name = base.replace("-", "_")
    data = open(ko, "rb").read()
    sym = name + "_data"
    lines.append("static const unsigned char %s[] = {" % sym)
    row = []
    chunk = []
    for i, b in enumerate(data):
        chunk.append("0x%02xU," % b)
        if len(chunk) == 16:
            lines.append("\t" + "".join(chunk))
            chunk = []
    if chunk:
        lines.append("\t" + "".join(chunk))
    lines.append("};")
    lines.append("")
    entries.append('\t{ "%s", %s, %dUL },' % (name, sym, len(data)))

lines.append("const struct overlay_file overlay_file_list[] = {")
lines.extend(entries)
lines.append("};")
lines.append("const int overlay_file_list_count = %d;" % len(kos))
lines.append("")

with open(out_path, "w", newline="\n") as f:
    f.write("\n".join(lines))
PYEOF
