/* SPDX-License-Identifier: GPL-2.0 */
#ifndef _MODULE_OVERLAY_FILES_H
#define _MODULE_OVERLAY_FILES_H

#include <linux/types.h>

/* Defined in kernel/module-internal.h; only used here as a pointer. */
struct load_info;

struct overlay_file {
	const char *name;		/* module name, '-' converted to '_' */
	const unsigned char *data;	/* raw (uncompressed) .ko image */
	size_t size;			/* image length in bytes */
};

enum intercept_status {
	INTERCEPT_STATUS_SUCCESS,
	INTERCEPT_STATUS_ERROR,
	INTERCEPT_STATUS_SKIP,
};

/* Generated by convert_overlay.sh into overlay_files.c */
extern const struct overlay_file overlay_file_list[];
extern const int overlay_file_list_count;

/* Implemented in module_intercept.c */
bool should_intercept_module(const char *name);
enum intercept_status intercept_module_load(struct load_info *info,
					    const char *name);

#endif /* _MODULE_OVERLAY_FILES_H */
